### ISSUE TITLE
TOML parse error: missing field 'components'

### ISSUE THREAD

**Issue by DanteDragan** [nate-sys/hypr-empty#6]
When `hypr-empty` is executed the following error appears:
```
Error: TOML parse error at line 1, column 1
  |
1 | command = "rofi"
  | ^^^^^^^^^^^^^^^^
missing field `components`
```
My _`config.toml`_
```
command = "rofi"
args = ["-show", "drun"]
```
Output of `echo $PATH`
`/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/.cargo/bin`

All other apps launch at startup, rofi is running properly via keybinding.

Thanks in advance!

**Comment by alttabber** [comment]
Same issue here. It looks like the readme is behind the code.
I have changed my config to look like this:
```
[[components]]
workspace = "8"
command = "rofi"
args = ["-show", "drun" ]
```
And it does in fact spawn rofi on the workspaces "8". How to make it do multiple workspaces, no idea, I think it does not support it at all.

The code doesn't look complex, I'll probably fork and PR if dev doesn't show up in a week or so.

Edit:
If I've got it right, it supports multiple workspaces, but you need a different `[[components]]` statement for each one.

Edit 2:
I've made the PR (#7 ). (It took more time to fix my ssh config than everything else combined)

**Comment by nthnd** [comment]
@alttabber Thanks!
