### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by gmankab** [nate-sys/hypr-empty#9]
```shell
./hypr-empty
Error: No such file or directory (os error 2)
./hypr-empty --help
Error: No such file or directory (os error 2)
```

distro is fedora silverblue

also i tried to run it in arch distrobox, same result

**Comment by nthnd** [comment]
Have you created the `~/.config/hypr-empty/config.toml` file as stated in the README?

**Comment by gmankab** [comment]
thank you, it helped

can you please add more user friendly error message?

feel free to close issue

**Comment by nthnd** [comment]
Noted ✅
